# Based on Neovim N Λ N O Theme by @ronisbr
# <https://github.com/ronisbr/nano-theme.nvim>
#
# Original theme released under the GNU General Public License v3.0

name = "Nano Default (Light)"

[palette]
rosewater = "#3d8b41"
flamingo = "#913aa0"
pink = "#913aa0"
mauve = "#913aa0"
red = "#c03830"
maroon = "#c03830"
peach = "#c49a00"
yellow = "#c49a00"
green = "#3d8b41"
teal = "#1a8f9e"
sky = "#1a8f9e"
sapphire = "#2e6fa3"
blue = "#2e6fa3"
lavender = "#2e6fa3"
text = "#3a3d38"
subtext_1 = "#484840"
subtext_0 = "#6e6c66"
overlay_2 = "#8b8b88"
overlay_1 = "#a2a29e"
overlay_0 = "#c4c4bc"
surface_2 = "#d1d1cb"
surface_1 = "#e8e8e2"
surface_0 = "#eeeee6"
base = "#fafaf7"
mantle = "#f3f3f0"
crust = "#eeeee6"
