vim.opt.hidden     = true
vim.opt.showmode   = false
vim.opt.shortmess  = vim.opt.shortmess + "c"
vim.opt.undofile   = true
vim.opt.updatetime = 1000
vim.opt.swapfile   = false
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.ignorecase = true
vim.opt.inccommand = "split"
vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.listchars = {
  tab      = ">-",
  eol      = "↵",
  nbsp     = "␣",
  trail    = "‧",
  extends  = "⟩",
  precedes = "⟨",
}
vim.opt.signcolumn = "yes"
