require("config.autopairs")
require("cfg.compe")
require("cfg.devicons")
require("cfg.easy_align")
require("cfg.floaterm")
-- require("cfg.galaxyline")
require("cfg.formatter")
require("cfg.gitsigns")
require("cfg.indent_blankline")
-- require("cfg.iris")
require("cfg.lspkind")
require("cfg.luasnip")
require("cfg.nvim_tree")
require("cfg.startify")
require("cfg.telescope")
require("cfg.treesitter")
require("cfg.trouble")
require("cfg.vim_test")

require("colorizer").setup()
require("telescope").load_extension("fzy_native") 
