ngs.nnoremap("<Leader>ff", "<Cmd>Telescope find_files<CR>")
ngs.nnoremap("<Leader>fg", "<Cmd>Telescope live_grep<CR>")
ngs.nnoremap("<Leader>fb", "<Cmd>Telescope buffers<CR>")
ngs.nnoremap("<Leader>fh", "<Cmd>Telescope help_tags<CR>")
ngs.nnoremap("<Leader>fr", "<Cmd>Telescope registers<CR>")
ngs.nnoremap("<Leader>ft", "<Cmd>Telescope treesitter<CR>")
