"$schema" = "https://starship.rs/config-schema.json"

[bun]
symbol = ""

[deno]
symbol = "󱍢"

[docker_context]
format = "[$symbol$context]($style) "
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = ""

[erlang]
symbol = ""

[fennel]
symbol = ""

[gleam]
symbol = "󰦥 "

[golang]
symbol = " "

[haxe]
symbol = ""

[kotlin]
symbol = ""

[lua]
symbol = " "

[nodejs]
symbol = ""

[ocaml]
symbol = ""

[perl]
symbol = ""

[php]
symbol = ""

[purescript]
symbol = ""

[python]
symbol = ""

[ruby]
symbol = ""

[rust]
symbol = ""

[typst]
symbol = ""

[swift]
symbol = ""

[zig]
symbol = ""
