"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[bun]
symbol = ""

[deno]
symbol = "󱍢"

[docker_context]
format = "[$symbol$context]($style) "
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = ""

[erlang]
symbol = ""

[fennel]
symbol = ""

[gleam]
symbol = "󰦥 "

[golang]
symbol = " "

[haxe]
symbol = ""

[kotlin]
symbol = ""

[lua]
symbol = " "

[nodejs]
symbol = ""

[ocaml]
symbol = ""

[perl]
symbol = ""

[php]
symbol = ""

[purescript]
symbol = ""

[python]
symbol = ""

[ruby]
symbol = ""

[rust]
symbol = ""

[typst]
symbol = ""

[swift]
symbol = ""

[zig]
symbol = ""
