# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

keybindings: vi

model: openrouter:deepseek/deepseek-chat-v3-0324
clients:
- type: openai-compatible
  name: openrouter
  api_base: https://openrouter.ai/api/v1
