[tools]
fastfetch = "latest"
jq = "latest"
neovim = "latest"
starship = "latest"
usage = "latest"
gum = "latest"
fd = "latest"
tmux = "latest"
rg = "latest"
gleam = "latest"
lazygit = "latest"
tree-sitter = "latest"
bat = "latest"
fzf = "latest"
black = "latest"
prettier = "latest"
stylua = "latest"
deno = "latest"
go = "latest"
lua = "latest"
lua-language-server = "latest"
node = "latest"
python = "latest"
rust = "latest"
rust-analyzer = "latest"
flyctl = "latest"
difftastic = "latest"
glow = "latest"
vale = "latest"
yazi = "latest"
sd = "latest"
bottom = "latest"
dust = "latest"
websocat = "latest"
aichat = "latest"
ruby = "latest"
shellcheck = "latest"
