require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "c",
    "c_sharp",
    "css",
    "dockerfile",
    "elixir",
    "erlang",
    "gdscript",
    "graphql",
    "javascript",
    "lua",
    "nix",
    "python",
    "regex",
    "ruby",
    "swift",
    "toml",
    "typescript",
    "yaml",
  },
  highlight = {enable = true, disable = {}},
  indent = {enable = true, disable = {"elixir"}},
  incremental_selection = {enable = true},
})
